In [3]:
import pandas as pd

df = pd.read_csv("data/raw/admission.csv")

# Remove whitespace from column names
df.columns = df.columns.str.strip()

# Remove the identifier
df = df.drop(columns=["Serial No."])

# Basic missing-value handling
df = df.dropna()

In [4]:
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR', 'CGPA',
       'Research', 'Chance of Admit'],
      dtype='str')

In [6]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=["Chance of Admit"])
y = df["Chance of Admit"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [7]:
X_train

     GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
249        321          111                  3  3.5  4.0  8.83         1
433        316          111                  4  4.0  5.0  8.54         0
19         303          102                  3  3.5  3.0  8.50         0
322        314          107                  2  2.5  4.0  8.27         0
332        308          106                  3  3.5  2.5  8.21         1
..         ...          ...                ...  ...  ...   ...       ...
106        329          111                  4  4.5  4.5  9.18         1
270        306          105                  2  2.5  3.0  8.22         1
348        302           99                  1  2.0  2.0  7.25         0
435        309          105                  2  2.5  4.0  7.68         0
102        314          106                  2  4.0  3.5  8.25         0

[400 rows x 7 columns]

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   GRE Score          500 non-null    int64
 1   TOEFL Score        500 non-null    int64
 2   University Rating  500 non-null    int64
 3   SOP                500 non-null    float64
 4   LOR                500 non-null    float64
 5   CGPA               500 non-null    float64
 6   Research           500 non-null    int64
 7   Chance of Admit    500 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 31.4 KB

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
GRE Score,500.0,316.47200,11.295148,290.00,308.0000,317.00,325.00,340.00
TOEFL Score,500.0,107.19200,6.081868,92.00,103.0000,107.00,112.00,120.00
University Rating,500.0,3.11400,1.143512,1.00,2.0000,3.00,4.00,5.00
SOP,500.0,3.37400,0.991004,1.00,2.5000,3.50,4.00,5.00
LOR,500.0,3.48400,0.925450,1.00,3.0000,3.50,4.00,5.00
CGPA,500.0,8.57644,0.604813,6.80,8.1275,8.56,9.04,9.92
Research,500.0,0.56000,0.496884,0.00,0.0000,1.00,1.00,1.00
Chance of Admit,500.0,0.72174,0.141140,0.34,0.6300,0.72,0.82,0.97